TWIBBONE_IMAGE:str      = 'https://dx18b9yoyun92.cloudfront.net/'
AVATAR:str              = 'https://di8f64wxtiymb.cloudfront.net/'
DOWLOAD_TWIBONE:str     = 'https://d23rv1d8scs4h0.cloudfront.net/'
TWIBBONIZE_METADATA:str = 'https://www.twibbonize.com/api2/'
TWIBBONE_SEARCH:str     = 'https://www.twibbonize.com/api1/campaign'
TWIBBONE_CLOUD_DRIVE:str = 'https://twb-results.s3-ap-southeast-1.amazonaws.com/'